tests:SlidingBuffer: Add an empty initializer to "const SlidingBuffer" declaration
[why]
Without the empty braces, clang on Darwin complains about a
missing user-defined default constructor:

error: default initialization of an object of const type
'const gul::SlidingBuffer<int>' without a user-provided default
constructor

[how]
Add a pair of empty braces.