SmallVector: Add missing include
[Why]
The compilation with GCC 15 fails with:
> In file included from tests/incl_SmallVector.cc:23:
> include/gul14/SmallVector.h:277:22: error: ‘uint32_t’ does not name a type [-Wtemplate-body]
>   277 |     using SizeType = uint32_t;
>       |                      ^~~~~~~~
> include/gul14/SmallVector.h:37:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
>    36 | #include "gul14/cat.h"
>   +++ |+#include <cstdint>
>    37 |

Signed-off-by: Soeren Grunewald <soeren.grunewald@desy.de>